version: "3.9"
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /tmp/swagger.yml
    volumes:
      - ./swagger.yml:/tmp/swagger.yml